### PR TITLE
Fix mockito version

### PR DESCRIPTION
**Pull request by rodolfomiranda**
Mockito version 1.5 causes  the test to failed, but works well when locked to 1.4.0

### CODE REVIEW

**Comment by pfeairheller** [comment]
We already did this on the main branch.  The hope with development was that we'd upgrade to the newest mockito.

**Comment by pfeairheller** [comment]
Also, to make it work you have to change test.yaml in .github for the GtiHub Action to work

**Comment by rodolfomiranda** [comment]
> We already did this on the main branch. The hope with development was that we'd upgrade to the newest mockito.

I'm being lazy :)

**Comment by rodolfomiranda** [comment]
> Also, to make it work you have to change test.yaml in .github for the GtiHub Action to work

this PR is for `test.yam`
But disregard that PR, I'll give a try upgrading mockito

**Review by pfeairheller — APPROVED** [review]

**Comment by pfeairheller** [comment]
Can you rebase this on new `main` and see if the builds now work?

**Comment by rodolfomiranda** [comment]
This PR in not needed

**Pull request closed without merging**
